name: gymflow
description: A gym management app scaffold using Provider.

# Prevents accidental publishing to pub.dev.
publish_to: 'none' 

# The version of your application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

# --- DEPENDENCIES ---
# Add your application dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # UI & ICONS
  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT
  provider: ^6.1.2

  # FIREBASE
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1

  # UTILITIES
  image_picker: ^1.1.2 # For picking images from the gallery or camera.
  intl: ^0.19.0      # For internationalization and date formatting.


# --- DEV DEPENDENCIES ---
# Dependencies used only for development and testing.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # A package with recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0

# --- FLUTTER CONFIGURATION ---
# The following section is specific to Flutter packages.
flutter:

  # Enables the Material Design UI library.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700