// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2RE4AMsB4S-u_ccs72U51FP4f0mI5pM',
    appId: '1:449612644405:web:141a10c9f8a560195f717c',
    messagingSenderId: '449612644405',
    projectId: 'gym-app-81b95',
    authDomain: 'gym-app-81b95.firebaseapp.com',
    storageBucket: 'gym-app-81b95.firebasestorage.app',
    measurementId: 'G-S7C5477WQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeqf2HokODyaTVQ_CtccO1sEoyqm9dCN0',
    appId: '1:449612644405:android:286f4085b60fe43b5f717c',
    messagingSenderId: '449612644405',
    projectId: 'gym-app-81b95',
    storageBucket: 'gym-app-81b95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA2I52aK69SSKnSP6MiLEC1_n1S172eIo',
    appId: '1:449612644405:ios:a51b74988652b6395f717c',
    messagingSenderId: '449612644405',
    projectId: 'gym-app-81b95',
    storageBucket: 'gym-app-81b95.firebasestorage.app',
    iosBundleId: 'com.example.gymflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA2I52aK69SSKnSP6MiLEC1_n1S172eIo',
    appId: '1:449612644405:ios:a51b74988652b6395f717c',
    messagingSenderId: '449612644405',
    projectId: 'gym-app-81b95',
    storageBucket: 'gym-app-81b95.firebasestorage.app',
    iosBundleId: 'com.example.gymflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL2RE4AMsB4S-u_ccs72U51FP4f0mI5pM',
    appId: '1:449612644405:web:ed9eb88557a2069f5f717c',
    messagingSenderId: '449612644405',
    projectId: 'gym-app-81b95',
    authDomain: 'gym-app-81b95.firebaseapp.com',
    storageBucket: 'gym-app-81b95.firebasestorage.app',
    measurementId: 'G-J0BSSCVBL6',
  );
}
